# Generated by Django 2.2 on 2019-04-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20190410_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='pre-username', max_length=255),
            preserve_default=False,
        ),
    ]
